#pragma once

#ifndef DEBUGOPTION_H
#define DEBUGOPTION_H

// These options allow developers/library users to tailor the debug output to their liking. 
// Some keywords below cover debug output of multiple classes:

// |||||||||||||||||||||||||||| Library: OrganicGLWinLib
// FACTORY
//	--CleaveSequenceFactory
//  --QMVoidFindCyclingDirection
// FACTORY_MERGER
//  --CategorizedLineMerger
//  --CategorizedLineInterceptsPointPreciseMerger
//  --CategorizedLinePartialBoundMerger
//  --CategorizedLineASliceMerger
// FRACTURER




enum class DebugOption
{
	// ||||||||||||||||||||||||||||||||||||||||||||||||| Options used by class SPolySet (OrganicGLWinLib)
	// generic options, for no specific SPoly
	SPOLYSET_TYPICAL,
	SPOLYSET_BOUNDARIES,
	SPOLYSET_ALL_SPOLY_MAIN,
	SPOLYSET_ALL_SPOLY_FACTORY,
	SPOLYSET_ALL_SPOLY_FACTORY_MERGER,
	SPOLYSET_ALL_FRACTURER,

	// specific poly options,
	SPECIFIC_SPOLY_MAIN,
	SPECIFIC_SPOLY_FACTORY,
	SPECIFIC_SPOLY_FACTORY_MERGER,
	SPECIFIC_FRACTURER_EXECUTION,
	SPECIFIC_SPOLY_CATEGORIZED_LINES,
	SPECIFIC_SPOLY_CATEGORIZED_LINE_COPLANAR_TESTS,

	// ||||||||||||||||||||||||||||||||||||||||||||||||| Options used by class MassZoneMaster (OrganicGLWinLib)
	// Options for OLD ZONE (See MassZoneMaster::oldZone, in OrganicGLWinLib)
	// debug options for Old zone (generic)
	MASSZONEMASTER_OLDZONE_PRINT_BOUNDARY_CATEGORIZED_LINES,				// prints the categorized lines in each boundary SPoly
	MASSZONEMASTER_OLDZONE_HALT_BETWEEN_BOUNDARY_SPOLY_CONSTRUCTION,		// waits for input between SPoly construction in the boundaries of a MassZoneBox.
	MASSZONEMASTER_OLDZONE_POINT_CLIPPING,

	// debug options for Old Zone, NEG_Z (North)
	MASSZONEMASTER_OLDZONE_NEG_Z_BOUNDARY_SPOLY_MAIN,
	MASSZONEMASTER_OLDZONE_NEG_Z_BOUNDARY_SPOLY_FACTORY,
	MASSZONEMASTER_OLDZONE_NEG_Z_BOUNDARY_SPOLY_FACTORY_MERGER,
	MASSZONEMASTER_OLDZONE_NEG_Z_BOUNDARY_FRACTURER,
	MASSZONEMASTER_OLDZONE_NEG_Z_BOUNDARY_CATEGORIZED_LINES,
	MASSZONEMASTER_OLDZONE_NEG_Z_BOUNDARY_CATEGORIZED_LINE_COPLANAR_TESTS,

	// debug options for Old zone, POS_X, (East)
	MASSZONEMASTER_OLDZONE_POS_X_BOUNDARY_SPOLY_MAIN,
	MASSZONEMASTER_OLDZONE_POS_X_BOUNDARY_SPOLY_FACTORY,
	MASSZONEMASTER_OLDZONE_POS_X_BOUNDARY_SPOLY_FACTORY_MERGER,
	MASSZONEMASTER_OLDZONE_POS_X_BOUNDARY_FRACTURER,
	MASSZONEMASTER_OLDZONE_POS_X_BOUNDARY_CATEGORIZED_LINES,
	MASSZONEMASTER_OLDZONE_POS_X_BOUNDARY_CATEGORIZED_LINE_COPLANAR_TESTS,

	// debug options for Old zone, POS_Z, (South)
	MASSZONEMASTER_OLDZONE_POS_Z_BOUNDARY_SPOLY_MAIN,
	MASSZONEMASTER_OLDZONE_POS_Z_BOUNDARY_SPOLY_FACTORY,
	MASSZONEMASTER_OLDZONE_POS_Z_BOUNDARY_SPOLY_FACTORY_MERGER,
	MASSZONEMASTER_OLDZONE_POS_Z_BOUNDARY_FRACTURER,
	MASSZONEMASTER_OLDZONE_POS_Z_BOUNDARY_CATEGORIZED_LINES,
	MASSZONEMASTER_OLDZONE_POS_Z_BOUNDARY_CATEGORIZED_LINE_COPLANAR_TESTS,

	// debug options for Old zone, NEG_X, (South)
	MASSZONEMASTER_OLDZONE_NEG_X_BOUNDARY_SPOLY_MAIN,
	MASSZONEMASTER_OLDZONE_NEG_X_BOUNDARY_SPOLY_FACTORY,
	MASSZONEMASTER_OLDZONE_NEG_X_BOUNDARY_SPOLY_FACTORY_MERGER,
	MASSZONEMASTER_OLDZONE_NEG_X_BOUNDARY_FRACTURER,
	MASSZONEMASTER_OLDZONE_NEG_X_BOUNDARY_CATEGORIZED_LINES,
	MASSZONEMASTER_OLDZONE_NEG_X_BOUNDARY_CATEGORIZED_LINE_COPLANAR_TESTS,

	// debug options for Old zone, POS_Y (Above)
	MASSZONEMASTER_OLDZONE_POS_Y_BOUNDARY_SPOLY_MAIN,
	MASSZONEMASTER_OLDZONE_POS_Y_BOUNDARY_SPOLY_FACTORY,
	MASSZONEMASTER_OLDZONE_POS_Y_BOUNDARY_SPOLY_FACTORY_MERGER,
	MASSZONEMASTER_OLDZONE_POS_Y_BOUNDARY_FRACTURER,
	MASSZONEMASTER_OLDZONE_POS_Y_BOUNDARY_CATEGORIZED_LINES,
	MASSZONEMASTER_OLDZONE_POS_Y_BOUNDARY_CATEGORIZED_LINE_COPLANAR_TESTS,

	// debug options for Old zone, NEG_Y (Below)
	MASSZONEMASTER_OLDZONE_NEG_Y_BOUNDARY_SPOLY_MAIN,
	MASSZONEMASTER_OLDZONE_NEG_Y_BOUNDARY_SPOLY_FACTORY,
	MASSZONEMASTER_OLDZONE_NEG_Y_BOUNDARY_SPOLY_FACTORY_MERGER,
	MASSZONEMASTER_OLDZONE_NEG_Y_BOUNDARY_FRACTURER,
	MASSZONEMASTER_OLDZONE_NEG_Y_BOUNDARY_CATEGORIZED_LINES,
	MASSZONEMASTER_OLDZONE_NEG_Y_BOUNDARY_CATEGORIZED_LINE_COPLANAR_TESTS,

	// Options for OLD ZONE (See MassZoneMaster::oldZone, in OrganicGLWinLib)
	MASSZONEMASTER_NEWZONE_PRINT_BOUNDARY_CATEGORIZED_LINES,				// prints the categorized lines in each boundary SPoly
	MASSZONEMASTER_NEWZONE_HALT_BETWEEN_BOUNDARY_SPOLY_CONSTRUCTION,		// waits for input between SPoly construction in the boundaries of a MassZoneBox.
	MASSZONEMASTER_NEWZONE_POINT_CLIPPING,

	// debug options for New zone, NEG_Z (North)
	MASSZONEMASTER_NEWZONE_NEG_Z_BOUNDARY_SPOLY_MAIN,
	MASSZONEMASTER_NEWZONE_NEG_Z_BOUNDARY_SPOLY_FACTORY,
	MASSZONEMASTER_NEWZONE_NEG_Z_BOUNDARY_SPOLY_FACTORY_MERGER,
	MASSZONEMASTER_NEWZONE_NEG_Z_BOUNDARY_FRACTURER,
	MASSZONEMASTER_NEWZONE_NEG_Z_BOUNDARY_CATEGORIZED_LINES,
	MASSZONEMASTER_NEWZONE_NEG_Z_BOUNDARY_CATEGORIZED_LINE_COPLANAR_TESTS,

	// debug options for New zone, POS_X, (East)
	MASSZONEMASTER_NEWZONE_POS_X_BOUNDARY_SPOLY_MAIN,
	MASSZONEMASTER_NEWZONE_POS_X_BOUNDARY_SPOLY_FACTORY,
	MASSZONEMASTER_NEWZONE_POS_X_BOUNDARY_SPOLY_FACTORY_MERGER,
	MASSZONEMASTER_NEWZONE_POS_X_BOUNDARY_FRACTURER,
	MASSZONEMASTER_NEWZONE_POS_X_BOUNDARY_CATEGORIZED_LINES,
	MASSZONEMASTER_NEWZONE_POS_X_BOUNDARY_CATEGORIZED_LINE_COPLANAR_TESTS,

	// debug options for New zone, POS_Z, (South)
	MASSZONEMASTER_NEWZONE_POS_Z_BOUNDARY_SPOLY_MAIN,
	MASSZONEMASTER_NEWZONE_POS_Z_BOUNDARY_SPOLY_FACTORY,
	MASSZONEMASTER_NEWZONE_POS_Z_BOUNDARY_SPOLY_FACTORY_MERGER,
	MASSZONEMASTER_NEWZONE_POS_Z_BOUNDARY_FRACTURER,
	MASSZONEMASTER_NEWZONE_POS_Z_BOUNDARY_CATEGORIZED_LINES,
	MASSZONEMASTER_NEWZONE_POS_Z_BOUNDARY_CATEGORIZED_LINE_COPLANAR_TESTS,

	// debug options for New zone, NEG_X, (South)
	MASSZONEMASTER_NEWZONE_NEG_X_BOUNDARY_SPOLY_MAIN,
	MASSZONEMASTER_NEWZONE_NEG_X_BOUNDARY_SPOLY_FACTORY,
	MASSZONEMASTER_NEWZONE_NEG_X_BOUNDARY_SPOLY_FACTORY_MERGER,
	MASSZONEMASTER_NEWZONE_NEG_X_BOUNDARY_FRACTURER,
	MASSZONEMASTER_NEWZONE_NEG_X_BOUNDARY_CATEGORIZED_LINES,
	MASSZONEMASTER_NEWZONE_NEG_X_BOUNDARY_CATEGORIZED_LINE_COPLANAR_TESTS,

	// debug options for New zone, POS_Y (Above)
	MASSZONEMASTER_NEWZONE_POS_Y_BOUNDARY_SPOLY_MAIN,
	MASSZONEMASTER_NEWZONE_POS_Y_BOUNDARY_SPOLY_FACTORY,
	MASSZONEMASTER_NEWZONE_POS_Y_BOUNDARY_SPOLY_FACTORY_MERGER,
	MASSZONEMASTER_NEWZONE_POS_Y_BOUNDARY_FRACTURER,
	MASSZONEMASTER_NEWZONE_POS_Y_BOUNDARY_CATEGORIZED_LINES,
	MASSZONEMASTER_NEWZONE_POS_Y_BOUNDARY_CATEGORIZED_LINE_COPLANAR_TESTS,

	// debug options for New zone, NEG_Y (Below)
	MASSZONEMASTER_NEWZONE_NEG_Y_BOUNDARY_SPOLY_MAIN,
	MASSZONEMASTER_NEWZONE_NEG_Y_BOUNDARY_SPOLY_FACTORY,
	MASSZONEMASTER_NEWZONE_NEG_Y_BOUNDARY_SPOLY_FACTORY_MERGER,
	MASSZONEMASTER_NEWZONE_NEG_Y_BOUNDARY_FRACTURER,
	MASSZONEMASTER_NEWZONE_NEG_Y_BOUNDARY_CATEGORIZED_LINES,
	MASSZONEMASTER_NEWZONE_NEG_Y_BOUNDARY_CATEGORIZED_LINE_COPLANAR_TESTS,

	// ||||||||||||||||||||||||||||||||||||||||||||||||| Options used by class CoplanarRelationships (OrganicGLWinLib)
	COPLANARRELATIONSHIP_SHOW_TRACKED_SPOLY_BORDER_LINES,

	// ||||||||||||||||||||||||||||||||||||||||||||||||| Options used by class CuttableTriangle (OrganicGLWinLib)
	REFERENCED_CUTTINGTRIANGLE_COMPARISON,
	REFERENCED_CUTTINGTRIANGLE_NONCOLINEAR_INTERSECT,
	REFERENCED_CUTTINGTRIANGLE_TJUNCTION_INTERSECT,
	REFERENCED_CUTTINGTRIANGLE_COLINEAR_INTERSECT,
	REFERENCED_CUTTINGTRIANGLE_QUAT_COLINEAR,
	REFERENCED_CUTTINGTRIANGLE_QUAT_INTERSECTING,
	REFERENCED_CUTTINGTRIANGLE_PBZ_TEST,
	REFERENCED_CUTTINGTRIANGLE_CYCLING_DIRECTION,
	REFERENCED_CUTTINGTRIANGLE_INTERSECT_ANALYZER_RESULT,
	REFERENCED_CUTTINGTRIANGLE_SLICE_ATTEMPTS,
	REFERENCED_CUTTINGTRIANGLE_TYPICAL_ATTEMPTS,
	REFERENCED_CUTTINGTRIANGLE_CUTLINEWELDER,
	REFERENCED_CUTTINGTRIANGLE_CUTTRIANGLEGROUPBUILDER
};

#endif