#pragma once

#ifndef DEBUGOPTION_H
#define DEBUGOPTION_H

// These options allow developers/library users to tailor the debug output to their liking. 
// Some keywords below cover debug output of multiple classes:

// |||||||||||||||||||||||||||| Library: OrganicGLWinLib
// FACTORY
//	--CleaveSequenceFactory
//  --QMVoidFindCyclingDirection
// FACTORY_MERGER
//  --CategorizedLineMerger
//  --CategorizedLineInterceptsPointPreciseMerger
//  --CategorizedLinePartialBoundMerger
//  --CategorizedLineASliceMerger




enum class DebugOption
{
	// generic options, for no specific SPoly
	SPOLYSET_TYPICAL,
	SPOLYSET_BOUNDARIES,
	SPOLYSET_ALL_SPOLY_MAIN,
	SPOLYSET_ALL_SPOLY_FACTORY,
	SPOLYSET_ALL_SPOLY_FACTORY_MERGER,
	SPOLYSET_ALL_FRACTURER,

	// specific poly options,
	SPECIFIC_SPOLY_MAIN,
	SPECIFIC_SPOLY_FACTORY,
	SPECIFIC_SPOLY_FACTORY_MERGER,
	SPECIFIC_FRACTURER_EXECUTION,
	SPECIFIC_SPOLY_CATEGORIZED_LINES,
	SPECIFIC_SPOLY_CATEGORIZED_LINE_COPLANAR_TESTS,

	// debug options for Old Zone, NEG_Z (North)
	MASSZONEMASTER_OLDZONE_NEG_Z_BOUNDARY_SPOLY_MAIN,
	MASSZONEMASTER_OLDZONE_NEG_Z_BOUNDARY_SPOLY_FACTORY,
	MASSZONEMASTER_OLDZONE_NEG_Z_BOUNDARY_SPOLY_FACTORY_MERGER,
	MASSZONEMASTER_OLDZONE_NEG_Z_BOUNDARY_FRACTURER,
	MASSZONEMASTER_OLDZONE_NEG_Z_BOUNDARY_CATEGORIZED_LINES,
	MASSZONEMASTER_OLDZONE_NEG_Z_BOUNDARY_CATEGORIZED_LINE_COPLANAR_TESTS,

	// debug options for Old zone, POS_X, (East)
	MASSZONEMASTER_OLDZONE_POS_X_BOUNDARY_SPOLY_MAIN,
	MASSZONEMASTER_OLDZONE_POS_X_BOUNDARY_SPOLY_FACTORY,
	MASSZONEMASTER_OLDZONE_POS_X_BOUNDARY_SPOLY_FACTORY_MERGER,
	MASSZONEMASTER_OLDZONE_POS_X_BOUNDARY_FRACTURER,
	MASSZONEMASTER_OLDZONE_POS_X_BOUNDARY_CATEGORIZED_LINES,
	MASSZONEMASTER_OLDZONE_POS_X_BOUNDARY_CATEGORIZED_LINE_COPLANAR_TESTS,

	// debug options for Old zone, POS_Z, (South)
	MASSZONEMASTER_OLDZONE_POS_Z_BOUNDARY_SPOLY_MAIN,
	MASSZONEMASTER_OLDZONE_POS_Z_BOUNDARY_SPOLY_FACTORY,
	MASSZONEMASTER_OLDZONE_POS_Z_BOUNDARY_SPOLY_FACTORY_MERGER,
	MASSZONEMASTER_OLDZONE_POS_Z_BOUNDARY_FRACTURER,
	MASSZONEMASTER_OLDZONE_POS_Z_BOUNDARY_CATEGORIZED_LINES,
	MASSZONEMASTER_OLDZONE_POS_Z_BOUNDARY_CATEGORIZED_LINE_COPLANAR_TESTS,

	// debug options for Old zone, NEG_X, (South)
	MASSZONEMASTER_OLDZONE_NEG_X_BOUNDARY_SPOLY_MAIN,
	MASSZONEMASTER_OLDZONE_NEG_X_BOUNDARY_SPOLY_FACTORY,
	MASSZONEMASTER_OLDZONE_NEG_X_BOUNDARY_SPOLY_FACTORY_MERGER,
	MASSZONEMASTER_OLDZONE_NEG_X_BOUNDARY_FRACTURER,
	MASSZONEMASTER_OLDZONE_NEG_X_BOUNDARY_CATEGORIZED_LINES,
	MASSZONEMASTER_OLDZONE_NEG_X_BOUNDARY_CATEGORIZED_LINE_COPLANAR_TESTS,

	// debug options for Old zone, POS_Y (Above)
	MASSZONEMASTER_OLDZONE_POS_Y_BOUNDARY_SPOLY_MAIN,
	MASSZONEMASTER_OLDZONE_POS_Y_BOUNDARY_SPOLY_FACTORY,
	MASSZONEMASTER_OLDZONE_POS_Y_BOUNDARY_SPOLY_FACTORY_MERGER,
	MASSZONEMASTER_OLDZONE_POS_Y_BOUNDARY_FRACTURER,
	MASSZONEMASTER_OLDZONE_POS_Y_BOUNDARY_CATEGORIZED_LINES,
	MASSZONEMASTER_OLDZONE_POS_Y_BOUNDARY_CATEGORIZED_LINE_COPLANAR_TESTS,

	// debug options for Old zone, NEG_Y (Below)
	MASSZONEMASTER_OLDZONE_NEG_Y_BOUNDARY_SPOLY_MAIN,
	MASSZONEMASTER_OLDZONE_NEG_Y_BOUNDARY_SPOLY_FACTORY,
	MASSZONEMASTER_OLDZONE_NEG_Y_BOUNDARY_SPOLY_FACTORY_MERGER,
	MASSZONEMASTER_OLDZONE_NEG_Y_BOUNDARY_FRACTURER,
	MASSZONEMASTER_OLDZONE_NEG_Y_BOUNDARY_CATEGORIZED_LINES,
	MASSZONEMASTER_OLDZONE_NEG_Y_BOUNDARY_CATEGORIZED_LINE_COPLANAR_TESTS

};

#endif